# Generated by Django 5.1.1 on 2024-09-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='Calories',
            field=models.IntegerField(default=0),
        ),
    ]
