# Generated by Django 5.1.1 on 2024-09-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_meal_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='meal_images/no_photo.png', upload_to='meal_images/'),
        ),
    ]
