# Generated by Django 5.1.1 on 2024-09-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_meal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='Calories',
            new_name='calories',
        ),
    ]
